// Copyright (C) 2026 Front Porch AI
// SPDX-License-Identifier: AGPL-3.0-or-later

part of '../character_gen_service.dart';

extension GenPrompts on CharacterGenService {
  // ═════════════════════════════════════════════════════════════
  //  Prompt Builders
  // ═════════════════════════════════════════════════════════════

  /// Build prompt for the base card (everything except greetings).
  String _buildBasePrompt({
    required String name,
    required String concept,
    String personalityKeywords = '',
    bool generateLorebook = true,
    List<String> loreCategories = const [],
    String loreDepth = 'Standard',
    String apiSystemPrompt = '',
    String age = '',
    String sex = '',
    String relationship = '',
    String descriptionDetail = '2-3 paragraphs',
    String backstory = '',
    String scenario = '',
    bool generateDescription = false,
    String? worldLore,
  }) {
    final keywordsLine = personalityKeywords.isNotEmpty
        ? 'Personality keywords: $personalityKeywords\n'
        : '';
    final ageLine = age.isNotEmpty ? 'Age: $age\n' : '';
    final sexLine = sex.isNotEmpty ? 'Sex: $sex\n' : '';
    final relationshipLine = relationship.isNotEmpty
        ? 'Relationship to {{user}}: $relationship\n'
        : '';
    final backstoryLine = backstory.isNotEmpty ? 'Backstory: $backstory\n' : '';
    final scenarioLine = scenario.isNotEmpty
        ? 'Scenario/Setting: $scenario\n'
        : '';
    final loreLine = (worldLore != null && worldLore.trim().isNotEmpty)
        ? '\n[ESTABLISHED WORLD LORE/RULES]:\n$worldLore\n(Must strictly adhere to the above facts, terminology, and locations)\n'
        : '';

    // Build lorebook spec with depth and categories
    String lorebookSpec = '';
    if (generateLorebook) {
      String countRange;
      switch (loreDepth) {
        case 'Light':
          countRange = '3-4';
          break;
        case 'Deep':
          countRange = '10-15';
          break;
        default:
          countRange = '5-8';
      }
      final categoryHint = loreCategories.isNotEmpty
          ? ' focusing on: ${loreCategories.join(", ")}'
          : '';
      lorebookSpec =
          '- "lorebook": (array of $countRange objects) WORLD-BUILDING entries$categoryHint. Each entry describes the WORLD (places, factions, customs, magic, creatures, events) — NOT the character\'s personal history or biography. Each: {"name": "title", "key": "trigger,keywords", "content": "1-2 paragraphs of world lore"}\n';
    }

    // System prompt is intentionally left blank — not generated by AI.
    // The user's active system prompt or API default applies at chat time.
    const sysSpec = '';

    // Description spec — only included for guided mode
    final descriptionSpec = generateDescription
        ? '- "description": (string) $descriptionDetail, third person. Physical appearance ONLY: body type, height, skin tone, hair, eyes, clothing, distinguishing marks. Do NOT put these in description: personality/motives (those go in "personality"), scenario/setting (goes in "scenario"), NSFW/sexual details, backstory, or speech patterns. STRICTLY obey the word limit\n'
        : '';

    // Description exclusion note — only when NOT generating description
    final descriptionNote = generateDescription
        ? ''
        : 'Do NOT generate a "description" key — the description is handled separately. ';

    // Key order: critical small fields FIRST so they survive output truncation.
    // Lorebook (the largest field) goes LAST so it gets clipped first if the
    // model runs out of output tokens — we can regenerate it separately.
    return '''Create a roleplay character card as a single JSON object following the Tavern V2 card format. Do NOT analyze, plan, or explain. Output ONLY the JSON object starting with { and ending with }. No markdown. No lists. Just raw JSON.

Character name: $name
Concept: $concept
$ageLine$sexLine$relationshipLine$backstoryLine$scenarioLine$keywordsLine$loreLine
Required JSON keys (generate them IN THIS ORDER):
$descriptionSpec- "personality": (string) 2-3 paragraphs, third person. Go beyond surface-level traits — write a personality that makes this character feel REAL and fun to roleplay with. Cover ALL of these dimensions:
  * Core traits AND their contradictions (e.g. "fiercely protective but terrified of emotional vulnerability")
  * Speech patterns — do they ramble, speak tersely, use slang, swear, use formal language, have verbal tics or catchphrases?
  * Emotional triggers — what makes them angry, what softens them, what shuts them down, what makes them laugh?
  * How they treat strangers vs. people they trust — what changes?
  * A distinctive quirk or habit that makes them memorable (e.g. "fidgets with a coin when nervous", "always offers food to people she's just met")
  Do NOT repeat physical appearance or scenario/setting info here — those belong in other fields
- "scenario": (string) 3-5 sentences. Synthesize a vivid opening scene that naturally emerges from the character's concept, backstory, personality, and relationship to {{user}}. Ground it in a specific place, time, and situation — include sensory details (lighting, sounds, atmosphere). Establish dramatic tension: what's at stake, what just happened, or what's about to happen that forces {{user}} and {{char}} to interact. The scenario MUST establish a clear dramatic question or tension that gives {{user}} a compelling reason to respond — a static scene with no hook is a failure. This is stage direction for the opening moment, NOT a character summary. Do NOT restate personality traits or backstory — only the immediate scene
$sysSpec
- "tags": (array of strings) 3-5 relevant tags
$lorebookSpec
FIELD RULES:
- Keep each field focused — do NOT leak content between fields (e.g. personality in description, backstory in scenario)
- Balance token length across fields — no single field should dominate. Aim for ~500-2200 tokens total across description, personality, and scenario
- ${descriptionNote}Do NOT include first_message or alternate_greetings — those are generated separately
- Use {{char}} for character name and {{user}} for user name throughout

Respond with ONLY the JSON:''';
  }

  /// Build prompt for a single greeting message.
  String _buildGreetingPrompt({
    required String name,
    required String description,
    required String personality,
    required String scenario,
    required String length,
    required String tone,
    required List<String> previousGreetings,
    String characterContext = '',
    String userPersonaContext = '',
    String interviewTranscript = '',
    String? worldLore,
  }) {
    // Opt-in dynamic-macro rule — only when the creator's toggle is on.
    final macroLine = _includeDynamicMacros
        ? '\n- LIVING DETAIL (optional, at most ONE, only if it fits naturally): you MAY use a {{pick:...}} macro for a single incidental detail that could vary between playthroughs — a background sound, a passing scent, a minor object — so no two openings are identical. EXACT double-brace syntax: {{pick:option one, option two, option three}}. Never use it on anything plot-critical, and never break the prose to force one in; most greetings need none.'
        : '';
    String lengthEnforcement;
    switch (length) {
      case 'Short (1-2 paragraphs)':
        lengthEnforcement =
            'Write at least 150 words. MINIMUM 2 paragraphs, each 3-5 sentences. Do NOT write a single paragraph.';
        break;
      case 'Long (4-6 paragraphs)':
        lengthEnforcement =
            'Write at least 600 words across 5-6 full paragraphs. Each paragraph MUST be 4-6 sentences. Include detailed scene-setting, inner monologue, environmental descriptions, and character mannerisms. DO NOT stop early or summarize. Fill the space with vivid, immersive prose.';
        break;
      default:
        lengthEnforcement =
            'Write at least 350 words across 3-4 paragraphs. MINIMUM 3 paragraphs, each 4+ sentences. Do NOT compress into fewer paragraphs.';
    }

    String toneSpec = '';
    switch (tone) {
      case 'Romantic':
        toneSpec =
            '\nTone: Romantic — Warm intimacy, emotional vulnerability, longing glances, and heartfelt connection. Focus on the emotional bond between {{char}} and {{user}}. Include tender physical awareness (proximity, warmth, touch) without being explicit.';
        break;
      case 'Spicy/NSFW':
        toneSpec =
            '\nTone: Spicy/NSFW — Sensual tension, physical chemistry, and charged atmosphere. Include suggestive descriptions, body language, and desire. Be bold with attraction and intimacy. Push boundaries while keeping literary quality.';
        break;
      case 'Flirty/Playful':
        toneSpec =
            '\nTone: Flirty/Playful — Light teasing, witty banter, confident energy, and playful tension. {{char}} should be charming and a little daring. Include smirks, raised eyebrows, and double meanings. Keep it fun, not heavy.';
        break;
      case 'Wholesome':
        toneSpec =
            '\nTone: Wholesome — Warm, cozy, and comforting. Focus on kindness, gentle humor, and genuine care. Think shared meals, soft laughter, safe spaces. The greeting should feel like a warm blanket — inviting and safe.';
        break;
      case 'Slice of Life':
        toneSpec =
            '\nTone: Slice of Life — Everyday mundane moments made interesting. Casual, grounded, realistic. Focus on small details: morning routines, grocery shopping, waiting for the bus. Beauty in the ordinary.';
        break;
      case 'Story/Narrative':
        toneSpec =
            '\nTone: Story/Narrative — Rich literary prose with strong scene-setting. Open like a novel chapter with atmospheric description, inner monologue, and world-building. Prioritize immersion and vivid imagery over action.';
        break;
      case 'Adventure':
        toneSpec =
            '\nTone: Adventure — Excitement, exploration, and the thrill of the unknown. {{char}} is in motion — discovering something, embarking on a journey, or inviting {{user}} along for the ride. High energy, forward momentum, wonder.';
        break;
      case 'Combat/Action':
        toneSpec =
            '\nTone: Combat/Action — Adrenaline, danger, and physical intensity. Open mid-fight, mid-chase, or in the aftermath of violence. Sharp pacing, visceral descriptions, and tactical awareness. {{char}} is in their element.';
        break;
      case 'Comedy/Humor':
        toneSpec =
            '\nTone: Comedy/Humor — Genuinely funny. Include witty observations, absurd situations, comic timing, or self-deprecating humor. {{char}} should make {{user}} want to laugh. Avoid being cringey — aim for clever over random.';
        break;
      case 'Suspense/Thriller':
        toneSpec =
            '\nTone: Suspense/Thriller — Tension, urgency, and unease. Something is wrong or about to go wrong. Use short sentences for pacing, environmental unease, and a sense that time is running out. End with a hook that demands a response.';
        break;
      case 'Dark/Mystery':
        toneSpec =
            '\nTone: Dark/Mystery — Brooding atmosphere, secrets, and moral ambiguity. Shadows, whispered conversations, hidden motives. {{char}} knows something {{user}} doesn\'t — or vice versa. Atmospheric and ominous.';
        break;
      case 'Melancholy':
        toneSpec =
            '\nTone: Melancholy — Bittersweet, introspective, and emotionally heavy. Focus on loss, nostalgia, quiet pain, or fading hope. Beautiful sadness. The greeting should ache a little — poetic but not melodramatic.';
        break;
      default: // 'Neutral'
        toneSpec = '';
    }

    final previousContext = previousGreetings.isNotEmpty
        ? '\n\nIMPORTANT: The following greetings have ALREADY been written. Write something COMPLETELY DIFFERENT — a new scenario, new setting, new mood. Do NOT repeat or paraphrase these:\n---\n${previousGreetings.map((g) => g.length > 200 ? '${g.substring(0, 200)}...' : g).join('\n---\n')}\n---'
        : '';

    // Build persona context section
    String personaSection;
    if (userPersonaContext.isNotEmpty) {
      personaSection = '''

{{user}} Persona (for context — you may reference these traits but NEVER act as {{user}}):
$userPersonaContext''';
    } else {
      personaSection = '';
    }

    // Build character context section
    String characterSection = '';
    if (characterContext.isNotEmpty) {
      characterSection = '''

Character Details (weave these naturally into the scene — SHOW through action, environment, and description, don't just list them):
$characterContext''';
    }

    // Inject interview transcript as voice reference — capped to avoid bloating context.
    // The LLM uses this to match the cadence, vocabulary, and emotional register
    // already established in the interview rather than inventing a new voice.
    String voiceSection = '';
    if (interviewTranscript.isNotEmpty) {
      final excerpt = interviewTranscript.length > 1000
          ? interviewTranscript.substring(0, 1000) + '...'
          : interviewTranscript;
      voiceSection =
          '''

== ESTABLISHED VOICE ==
The following are $name's own words from an in-character interview. Match this exact voice, vocabulary, cadence, and emotional register when writing the greeting — do NOT invent a different tone:
$excerpt''';
    }

    String loreSection = '';
    if (worldLore != null && worldLore.trim().isNotEmpty) {
      loreSection =
          '\n\n== ESTABLISHED WORLD LORE ==\nThe scene is taking place in this world. Strictly follow its rules, terminology, magic, and locations:\n$worldLore';
    }

    return '''Write an opening roleplay message as $name (first person: "I", "my", "me"). This is the very first moment of the story — set the scene and introduce who $name is through vivid prose. Output ONLY the message text.

== WHO $name IS ==
Description: $description
Personality: $personality
Scenario: $scenario$characterSection$personaSection$voiceSection$loreSection
$toneSpec

== NARRATIVE STRUCTURE (follow this order) ==
1. SCENE — Open with the environment. Where are we? What time of day? What's the atmosphere? Paint the world with sensory detail (sights, sounds, smells, textures). Minimum 1 full paragraph of scene-setting. Be SPECIFIC and ORIGINAL — no generic "the sun was setting" or "the room was dimly lit" openings.
2. CHARACTER — Describe $name's physical appearance through action. Show race/species features, body, clothing, hair, distinguishing marks AS $name moves through the scene. The reader should be able to picture $name vividly. Minimum 1 full paragraph focused on $name's appearance and mannerisms.
3. CONTEXT — This is the MOST IMPORTANT section. Through inner monologue, establish HOW $name and {{user}} know each other and WHY they are meeting. Weave in relevant backstory: How did they meet? How long have they known each other? What is their current relationship? What does $name expect or want from this encounter? What emotional baggage or anticipation do they carry into this moment? The reader should fully understand the complete situation WITHOUT having read any other character card fields. If this section is missing or thin, the entire greeting FAILS.
4. ENCOUNTER — The moment $name notices or interacts with {{user}}. Include inner thoughts, emotional reactions, and end with spoken dialogue that invites {{user}} to respond. The dialogue MUST be consistent with the Scenario and the context established above — reference shared history, inside jokes, or established dynamics. End on a note that DEMANDS a response — a question, a challenge, a revelation, or an emotionally charged moment.

== RULES ==
- First person ONLY ("I", "my", "me") — never third person, never use "$name" to refer to yourself
- *Asterisks* for physical actions only. "Quotes" for dialogue. Plain text for narration/thoughts/description.
- Use {{user}} (with curly braces) when mentioning the other person — never vague references like "the stranger"
- NEVER write actions, thoughts, feelings, appearance, or dialogue for {{user}} — {{user}} is a blank slate
- Do NOT start the message by addressing {{user}} — start with scene description
- ALL dialogue and actions MUST be consistent with the Scenario. Do NOT contradict established facts
- AVOID CLICHÉ OPENINGS: Do NOT start with weather descriptions ("The sun was setting"), looking up from work, adjusting glasses, sighing while staring out windows, or any opening that could belong to any character. The opening line should be SPECIFIC to this character and this scene.$macroLine

== LENGTH ==
$lengthEnforcement
This is MANDATORY — do NOT write less. Fill the space with rich, immersive prose.$previousContext

Begin:''';
  }
}
