// Copyright (C) 2026 Front Porch AI
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This file is part of Front Porch AI.
//
// Front Porch AI is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Front Porch AI is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Front Porch AI. If not, see <https://www.gnu.org/licenses/>.

/// Standard emotion labels for character expression images.
///
/// Based on the 28-class go-emotions ONNX model
/// (Cohee/distilbert-base-uncased-go-emotions-onnx) with two additions:
/// 'affection' and 'anticipation' for richer expression variety.
class EmotionLabels {
  /// All 28 standard go-emotions labels plus 2 additions.
  static const List<String> all = [
    'admiration',
    'affection',
    'amusement',
    'anger',
    'annoyance',
    'anticipation',
    'approval',
    'caring',
    'confusion',
    'curiosity',
    'desire',
    'disappointment',
    'disapproval',
    'disgust',
    'embarrassment',
    'excitement',
    'fear',
    'gratitude',
    'grief',
    'joy',
    'love',
    'nervousness',
    'optimism',
    'pride',
    'realization',
    'relief',
    'remorse',
    'sadness',
    'surprise',
    'neutral',
  ];

  /// Emoji representation for each standard emotion label.
  static const Map<String, String> emoji = {
    'admiration': '🤩',
    'affection': '💕',
    'amusement': '😄',
    'anger': '😠',
    'annoyance': '😤',
    'anticipation': '👀',
    'approval': '👍',
    'caring': '🤗',
    'confusion': '😕',
    'curiosity': '🧐',
    'desire': '🥵',
    'disappointment': '😞',
    'disapproval': '👎',
    'disgust': '🤢',
    'embarrassment': '😳',
    'excitement': '🤩',
    'fear': '😨',
    'gratitude': '🙏',
    'grief': '😭',
    'joy': '😁',
    'love': '😍',
    'nervousness': '😰',
    'optimism': '😊',
    'pride': '😎',
    'realization': '💡',
    'relief': '😌',
    'remorse': '😔',
    'sadness': '😢',
    'surprise': '😲',
    'neutral': '😐',
  };

  /// Maps nuanced LLM-generated emotion words to standard expression labels.
  ///
  /// The Realism Engine LLM produces nuanced words like "elated", "wistful",
  /// "starstruck", etc. This mapping translates them to one of the standard
  /// labels so the correct expression sprite can be shown.
  ///
  /// If an emotion word is not found in this map, the caller should trigger
  /// an LLM re-classification to pick from [all] labels.
  static const Map<String, String> nuancedToStandard = {
    // -> admiration
    'in_awe': 'admiration',
    'impressed': 'admiration',
    'reverent': 'admiration',
    'awed': 'admiration',
    'marveling': 'admiration',
    'respectful': 'admiration',
    // -> affection
    'fond': 'affection',
    'tender': 'affection',
    'warm': 'affection',
    'doting': 'affection',
    'attached': 'affection',
    'devoted': 'affection',
    // -> amusement
    'amused': 'amusement',
    'playful': 'amusement',
    'cheerful': 'amusement',
    'lighthearted': 'amusement',
    'teasing': 'amusement',
    'entertained': 'amusement',
    'humorous': 'amusement',
    'joking': 'amusement',
    // -> anger
    'angry': 'anger',
    'furious': 'anger',
    'enraged': 'anger',
    'irate': 'anger',
    'livid': 'anger',
    'hostile': 'anger',
    'resentful': 'anger',
    'outraged': 'anger',
    'seething': 'anger',
    'infuriated': 'anger',
    'prickly': 'anger',
    'bitter': 'anger',
    'vengeful': 'anger',
    'fuming': 'anger',
    // -> annoyance
    'annoyed': 'annoyance',
    'irritated': 'annoyance',
    'exasperated': 'annoyance',
    'frustrated': 'annoyance',
    'bothered': 'annoyance',
    'aggravated': 'annoyance',
    'petrified': 'annoyance',
    'fed_up': 'annoyance',
    // -> anticipation
    'eager': 'anticipation',
    'expectant': 'anticipation',
    'hovering': 'anticipation',
    'looking_forward': 'anticipation',
    'impatient': 'anticipation',
    'keen': 'anticipation',
    // -> approval
    'approving': 'approval',
    'satisfied': 'approval',
    'pleased': 'approval',
    'content': 'approval',
    'delighted': 'approval',
    'thoroughly_pleased': 'approval',
    // -> caring
    'caring': 'caring',
    'compassionate': 'caring',
    'sympathetic': 'caring',
    'empathetic': 'caring',
    'protective': 'caring',
    'nurturing': 'caring',
    'concerned': 'caring',
    'supportive': 'caring',
    'solicitous': 'caring',
    // -> confusion
    'confused': 'confusion',
    'conflicted': 'confusion',
    'bewildered': 'confusion',
    'perplexed': 'confusion',
    'puzzled': 'confusion',
    'baffled': 'confusion',
    'disoriented': 'confusion',
    'lost': 'confusion',
    'uncertain': 'confusion',
    // -> curiosity
    'curious': 'curiosity',
    'inquisitive': 'curiosity',
    'interested': 'curiosity',
    'intrigued': 'curiosity',
    'wondering': 'curiosity',
    '探究': 'curiosity',
    // -> desire
    'desire': 'desire',
    'wanting': 'desire',
    'craving': 'desire',
    'yearning': 'desire',
    'longing': 'desire',
    'hungry': 'desire',
    'thirsty': 'desire',
    'needy': 'desire',
    'covetous': 'desire',
    'lusting': 'desire',
    'aroused': 'desire',
    'flirtatious': 'desire',
    'smoldering': 'desire',
    'passionate': 'desire',
    'enticed': 'desire',
    // -> disappointment
    'disappointed': 'disappointment',
    'let_down': 'disappointment',
    'dismayed': 'disappointment',
    'disillusioned': 'disappointment',
    'crestfallen': 'disappointment',
    'disheartened': 'disappointment',
    'deflated': 'disappointment',
    // -> disgust
    'disgusted': 'disgust',
    'revolted': 'disgust',
    'sickened': 'disgust',
    'repulsed': 'disgust',
    'appalled': 'disgust',
    'offended': 'disgust',
    'repelled': 'disgust',
    // -> embarrassment
    'embarrassed': 'embarrassment',
    'flustered': 'embarrassment',
    'bashful': 'embarrassment',
    'mortified': 'embarrassment',
    'humiliated': 'embarrassment',
    'shy': 'embarrassment',
    'self_conscious': 'embarrassment',
    'awkward': 'embarrassment',
    'abashed': 'embarrassment',
    'blushing': 'embarrassment',
    // -> excitement
    'excited': 'excitement',
    'thrilled': 'excitement',
    'pumped': 'excitement',
    'exhilarated': 'excitement',
    'energized': 'excitement',
    'revved_up': 'excitement',
    'buzzing': 'excitement',
    'animated': 'excitement',
    'lively': 'excitement',
    'spirited': 'excitement',
    'vivacious': 'excitement',
    // -> fear
    'fearful': 'fear',
    'scared': 'fear',
    'afraid': 'fear',
    'terrified': 'fear',
    'panicked': 'fear',
    'dread': 'fear',
    'daunted': 'fear',
    'horrified': 'fear',
    'timid': 'fear',
    'frightened': 'fear',
    'spooked': 'fear',
    'tense': 'fear',
    // -> gratitude
    'grateful': 'gratitude',
    'thankful': 'gratitude',
    'appreciative': 'gratitude',
    'indebted': 'gratitude',
    'obliged': 'gratitude',
    // -> grief
    'grieving': 'grief',
    'mournful': 'grief',
    'heartbroken': 'grief',
    'devastated': 'grief',
    'sorrowful': 'grief',
    'bereaved': 'grief',
    'lamenting': 'grief',
    'desolate': 'grief',
    // -> joy
    'joy': 'joy',
    'happy': 'joy',
    'elated': 'joy',
    'ecstatic': 'joy',
    'overjoyed': 'joy',
    'joyful': 'joy',
    'blissful': 'joy',
    'jubilant': 'joy',
    'euphoric': 'joy',
    'radiant': 'joy',
    'gleeful': 'joy',
    'merry': 'joy',
    'cheerful_mood': 'joy',
    'beaming': 'joy',
    'glowing': 'joy',
    // -> love
    'love': 'love',
    'in_love': 'love',
    'adoring': 'love',
    'smitten': 'love',
    'starstruck': 'love',
    'infatuated': 'love',
    'enamored': 'love',
    'enamoured': 'love',
    'deeply_attached': 'love',
    'romantic': 'love',
    'cherishing': 'love',
    'worshipping': 'love',
    // -> nervousness
    'nervous': 'nervousness',
    'jittery': 'nervousness',
    'anxious': 'nervousness',
    'worried': 'nervousness',
    'stressed': 'nervousness',
    'uneasy': 'nervousness',
    'apprehensive': 'nervousness',
    'on_edge': 'nervousness',
    'sweating': 'nervousness',
    'edgy': 'nervousness',
    // -> optimism
    'optimistic': 'optimism',
    'hopeful': 'optimism',
    'positive': 'optimism',
    'upbeat': 'optimism',
    'confident': 'optimism',
    'encouraged': 'optimism',
    'inspired': 'optimism',
    'buoyant': 'optimism',
    // -> pride
    'proud': 'pride',
    'triumphant': 'pride',
    'accomplished': 'pride',
    'self_assured': 'pride',
    'self_confident': 'pride',
    'cocky': 'pride',
    'smug': 'pride',
    'vindicated': 'pride',
    'superior': 'pride',
    // -> realization
    'realizing': 'realization',
    'understanding': 'realization',
    'enlightened': 'realization',
    'awakened': 'realization',
    'dawning': 'realization',
    'comprehending': 'realization',
    'epiphany': 'realization',
    'clicking': 'realization',
    // -> remorse
    'remorseful': 'remorse',
    'guilty': 'remorse',
    'regretful': 'remorse',
    'ashamed': 'remorse',
    'penitent': 'remorse',
    'sorry': 'remorse',
    'contrite': 'remorse',
    'repentant': 'remorse',
    'self_reproach': 'remorse',
    // -> sadness
    'sad': 'sadness',
    'sadness': 'sadness',
    'melancholy': 'sadness',
    'wistful': 'sadness',
    'downcast': 'sadness',
    'blue': 'sadness',
    'gloomy': 'sadness',
    'somber': 'sadness',
    'dejected': 'sadness',
    'depressed': 'sadness',
    'downhearted': 'sadness',
    'low_spirited': 'sadness',
    'miserable': 'sadness',
    'forlorn': 'sadness',
    'lonely': 'sadness',
    'isolated': 'sadness',
    'blue_mood': 'sadness',
    'heavy_hearted': 'sadness',
    'sullen': 'sadness',
    // -> surprise
    'surprised': 'surprise',
    'shocked': 'surprise',
    'astonished': 'surprise',
    'stunned': 'surprise',
    'startled': 'surprise',
    'taken_aback': 'surprise',
    'flabbergasted': 'surprise',
    'amazed': 'surprise',
    'speechless': 'surprise',
    'dumbfounded': 'surprise',
    'unexpected': 'surprise',
    // -> calm / relaxed -> neutral or approval
    'calm': 'neutral',
    'relaxed': 'neutral',
    'at_peace': 'neutral',
    'serene': 'neutral',
    'composed': 'neutral',
    'collected': 'neutral',
    'unbothered': 'neutral',
    'poised': 'neutral',
    'tranquil': 'neutral',
    // -> guarded / stoic -> neutral
    'guarded': 'neutral',
    'stoic': 'neutral',
    'reserved': 'neutral',
    'controlled': 'neutral',
    'restrained': 'neutral',
    'detached': 'neutral',
    'aloof': 'neutral',
    'distant': 'neutral',
    'indifferent': 'neutral',
    'apathetic': 'neutral',
    'blank': 'neutral',
    'settled': 'neutral',
    'neutral_mood': 'neutral',
    // -> suspicious -> confusion
    'suspicious': 'confusion',
    'wary': 'confusion',
    'doubtful': 'confusion',
    'skeptical': 'confusion',
    'distrustful': 'confusion',
    'cynical': 'confusion',
    'mistrustful': 'confusion',
    'guarded_suspicion': 'confusion',
    // -> determined -> optimism
    'determined': 'optimism',
    'resolute': 'optimism',
    'steadfast': 'optimism',
    'unyielding': 'optimism',
    'persistent': 'optimism',
    'driven': 'optimism',
    'focused': 'optimism',
    'committed': 'optimism',
    // -> vulnerable -> fear
    'vulnerable': 'fear',
    'exposed': 'fear',
    'defenseless': 'fear',
    'fragile': 'fear',
    'weak': 'fear',
    // -> playful -> amusement
    'mischievous': 'amusement',
    'naughty': 'amusement',
    'cheeky': 'amusement',
    'waggish': 'amusement',
    // -> contemplative -> curiosity
    'contemplative': 'curiosity',
    'reflective': 'curiosity',
    'thoughtful': 'curiosity',
    'pensive': 'curiosity',
    'meditative': 'curiosity',
    'philosophical': 'curiosity',
    // -> empowered -> pride
    'empowered': 'pride',
    'strong': 'pride',
    'capable': 'pride',
    'assertive': 'pride',
    'bold': 'pride',
    'fearless': 'pride',
    // -> submissive -> desire
    'submissive': 'desire',
    'yielding': 'desire',
    'compliant': 'desire',
    'obedient': 'desire',
    'docile': 'desire',
    // -> playful_affection -> affection
    'teasing_affection': 'affection',
    'playful_love': 'affection',
    'affectionate': 'affection',
    'loving': 'affection',
    // -> comfort -> caring
    'comforting': 'caring',
    'soothing': 'caring',
    'reassuring': 'caring',
    'consoling': 'caring',
    'gentle': 'caring',
    // -> triumphant -> pride
    'victorious': 'pride',
    'conquering': 'pride',
    'exultant': 'pride',
    // -> nostalgic -> sadness
    'nostalgic': 'sadness',
    'wistful_longing': 'sadness',
    'sentimental': 'sadness',
    'maudlin': 'sadness',
    // -> relieved -> approval
    'relieved': 'relief',
    'unburdened': 'relief',
    'at_ease': 'relief',
    'comfortable': 'relief',
    // -> disapproval
    'disapproving': 'disapproval',
    'judgmental': 'disapproval',
    'condemning': 'disapproval',
    'scornful': 'disapproval',
    'disdainful': 'disapproval',
    // -> playful_anger -> annoyance
    'playfully_angry': 'annoyance',
    'mock_angry': 'annoyance',
    'petulant': 'annoyance',
    'pettish': 'annoyance',
    'irritable': 'annoyance',
    // -> sly -> amusement
    'sly': 'amusement',
    'cunning': 'amusement',
    'calculating': 'amusement',
    'devious': 'amusement',
    'crafty': 'amusement',
    // -> mysterious -> curiosity
    'mysterious': 'curiosity',
    'enigmatic': 'curiosity',
    'cryptic': 'curiosity',
    'elusive': 'curiosity',
    // -> playful_desire -> desire
    'playfully_flirtatious': 'desire',
    'coquettish': 'desire',
    'alluring': 'desire',
    'seductive': 'desire',
    'tempting': 'desire',
    'enticing': 'desire',
    'captivating': 'desire',
    // -> vulnerable_affection -> affection
    'vulnerable_love': 'affection',
    'open_hearted': 'affection',
    'exposed_emotionally': 'affection',
    // -> bittersweet -> sadness
    'bittersweet': 'sadness',
    'bittersweet_joy': 'sadness',
    'bittersweet_love': 'sadness',
    // -> playful_sadness -> sadness
    'sad_but_smiling': 'sadness',
    'tearful_smile': 'sadness',
    // -> overwhelmed -> fear
    'overwhelmed': 'fear',
    'overpowered': 'fear',
    'consumed': 'fear',
    'swamped': 'fear',
    // -> playful_pride -> pride
    'playfully_proud': 'pride',
    'bragging': 'pride',
    'boastful': 'pride',
    // -> tender_anger -> anger
    'tender_anger': 'anger',
    'hurt_angry': 'anger',
    'wronged': 'anger',
    // -> playful_fear -> fear
    'playfully_scared': 'fear',
    'mock_terrified': 'fear',
    'goosebumps': 'fear',
    // -> settled -> neutral
    'at_rest': 'neutral',
    'peaceful': 'neutral',
  };

  /// Prompt template for LLM re-classification when the emotion is unmapped.
  ///
  /// Use this to ask the LLM to classify an unknown emotion word into one of
  /// the standard labels. Send this as a quick single-call prompt and parse
  /// the response for a word from [all].
  static String buildReclassifyPrompt(String unknownEmotion) {
    final labels = all.join(', ');
    return 'Classify the emotion "$unknownEmotion" into exactly ONE of these labels: '
        '$labels.\n'
        'Respond with ONLY the label name, nothing else.';
  }
}
