// Copyright (C) 2026 Front Porch AI
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Proof tests for the Photo Understanding (offline captioner) Dart port of
// the SmolVLM pipeline. The prompt-id and decode goldens were generated by
// the reference HF Idefics3Processor/tokenizer (see smolvlm_golden_fixtures);
// if buildSmolVlmPromptIds or the byte-level decoder ever drift from the
// reference, the model receives garbage and captions silently degrade — these
// tests make that drift loud instead.
//
// The full ONNX end-to-end run (real model, real native lib) is env-gated:
//   FPAI_CAPTION_MODEL_DIR=<dir with the 4 artifacts> \
//   LD_LIBRARY_PATH=<onnxruntime_v2 plugin>/linux flutter test <this file>
// so CI (no 515MB model) skips it while local verification exercises the
// entire pipeline including tensors, KV-cache chaining, and decoding.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:image/image.dart' as img;

import 'package:front_porch_ai/services/caption/smolvlm_engine.dart';
import 'package:front_porch_ai/services/caption/smolvlm_preprocess.dart';
import 'package:front_porch_ai/services/caption/smolvlm_prompt.dart';

import 'smolvlm_golden_fixtures.dart';

void main() {
  group('buildSmolVlmPromptIds matches the reference processor', () {
    test('2x2 grid (the common case for chat attachments)', () {
      expect(buildSmolVlmPromptIds(rows: 2, cols: 2), kGoldenPromptIdsGrid2x2);
    });

    test('1x2 grid (extreme landscape)', () {
      expect(buildSmolVlmPromptIds(rows: 1, cols: 2), kGoldenPromptIdsGrid1x2);
    });

    test('2x1 grid (extreme portrait)', () {
      expect(buildSmolVlmPromptIds(rows: 2, cols: 1), kGoldenPromptIdsGrid2x1);
    });
  });

  group('SmolVlmVocabDecoder', () {
    // Round-trip golden from the reference tokenizer — exercises byte-level
    // BPE reversal including the em-dash (multi-byte UTF-8), "$", "%", and
    // the leading-space Ġ convention.
    const goldenIds = [
      10345, 10147, 1717, 7680, 359, 12894, 335, 253, 11986, 21714, 30, 378, //
      2644, 506, 25748, 553, 253, 13095, 1841, 357, 3499, 1885, 33, 34, 30,
      37, 32, 365, 37, 32, 21, 767, 595,
    ];
    const goldenText =
        "Two tabby cats are lying on a pink blanket. The cat's collar has a "
        'bell — it costs \$12.50 (50% off).';

    test('decodes the reference token stream byte-for-byte', () {
      // Minimal vocab slice generated from the real tokenizer.json (only the
      // entries the golden stream uses) so this always runs, model or not.
      final decoder = SmolVlmVocabDecoder.fromTokenizerJson(
        File(
          'test/services/caption/tokenizer_mini_fixture.json',
        ).readAsStringSync(),
      );
      expect(decoder.decode(goldenIds), goldenText);
      // Special tokens are skipped, not rendered.
      expect(
        decoder.decode([kSmolVlmEndOfUtterance, ...goldenIds.take(2)]),
        'Two tab',
      );
    });
  });

  group('preprocessForSmolVlm', () {
    test('common photo sizes produce the reference 2x2 grid + global', () {
      for (final (w, h) in [(960, 626), (640, 480), (1024, 1024), (300, 200)]) {
        final frames = preprocessForSmolVlm(img.Image(width: w, height: h));
        expect(frames.rows, 2, reason: '$w x $h');
        expect(frames.cols, 2, reason: '$w x $h');
        expect(frames.frameCount, 5, reason: '$w x $h');
        expect(frames.pixelValues.length, 5 * 3 * 512 * 512);
        expect(frames.pixelMask.length, 5 * 512 * 512);
      }
    });

    test('extreme aspect ratios produce the reference smaller grids', () {
      final landscape = preprocessForSmolVlm(
        img.Image(width: 1024, height: 100),
      );
      expect((landscape.rows, landscape.cols), (1, 2));
      expect(landscape.frameCount, 3);
      final portrait = preprocessForSmolVlm(
        img.Image(width: 100, height: 1024),
      );
      expect((portrait.rows, portrait.cols), (2, 1));
      expect(portrait.frameCount, 3);
    });

    test('normalization maps a constant gray to (v*2/255 - 1)', () {
      final src = img.Image(width: 600, height: 600);
      img.fill(src, color: img.ColorRgb8(128, 64, 0));
      final frames = preprocessForSmolVlm(src);
      // First tile, first pixel of each channel plane.
      const plane = 512 * 512;
      expect(frames.pixelValues[0], closeTo(128 * 2 / 255 - 1, 1e-4));
      expect(frames.pixelValues[plane], closeTo(64 * 2 / 255 - 1, 1e-4));
      expect(frames.pixelValues[2 * plane], closeTo(-1.0, 1e-4));
    });

    // NOTE: the 16-bit-PNG normalization fix (rNormalized instead of raw p.r)
    // is intentionally NOT unit-tested here: the image package can't
    // faithfully synthesize a uint16 PNG in-harness (a constructed uint16
    // image reads back as zero through encode→decode), so any such test would
    // be a false guard. The fix is verified by a runnable reproduction (see
    // the code review notes) and by the env-gated E2E; the 8-bit normalization
    // test above pins the common path.

    test('only the global frame carries padding, mirrored in the mask', () {
      final frames = preprocessForSmolVlm(img.Image(width: 1024, height: 100));
      const plane = 512 * 512;
      final globalBase = 2 * plane; // 2 tiles then global
      // Canvas 1024x512 → global 512x256: rows 0..255 valid, rest padded.
      expect(frames.pixelMask[globalBase + 255 * 512], isTrue);
      expect(frames.pixelMask[globalBase + 256 * 512], isFalse);
      // Tile frames are never padded.
      expect(frames.pixelMask.take(2 * plane).every((b) => b), isTrue);
      // Padded pixels are 0.0 in normalized space.
      final pixBase = 2 * 3 * plane; // global frame's R plane
      expect(frames.pixelValues[pixBase + 256 * 512], 0.0);
    });
  });

  group('end-to-end ONNX caption (env-gated)', () {
    test(
      'captions a real photo with the real model',
      () async {
        final modelDir = _modelDirFromEnv();
        if (modelDir == null) {
          markTestSkipped(
            'set FPAI_CAPTION_MODEL_DIR (and LD_LIBRARY_PATH to the '
            'onnxruntime_v2 native lib) to run the full pipeline',
          );
          return;
        }
        final testImage = File('test/services/caption/e2e_test_photo.jpg');
        if (!testImage.existsSync()) {
          markTestSkipped('no e2e_test_photo.jpg fixture present');
          return;
        }
        final caption = await _captionDirect(modelDir, testImage);
        expect(caption, isNotNull);
        expect(caption!.length, greaterThan(30));
        // The fixture is the classic COCO two-cats photo.
        expect(caption.toLowerCase(), contains('cat'));
        // ignore: avoid_print
        print('E2E caption: $caption');
      },
      timeout: const Timeout(Duration(minutes: 15)),
    );
  });
}

Directory? _modelDirFromEnv() {
  final path = Platform.environment['FPAI_CAPTION_MODEL_DIR'];
  if (path == null || path.isEmpty) return null;
  final dir = Directory(path);
  return dir.existsSync() ? dir : null;
}

/// Run the engine directly against an explicit model dir (bypasses the
/// service's `<root>/caption_model` convention for the env-gated test).
Future<String?> _captionDirect(Directory modelDir, File image) {
  return SmolVlmEngine.caption(
    modelDirPath: modelDir.path,
    imagePath: image.path,
  );
}
